### PR TITLE
Internal/update api signatures

### PR DESCRIPTION
**Pull request by Jesulonimi21**
This PR updates the function signature of the contract API functions to match the optimizations made in the rc branch

### CODE REVIEW

**Comment by Jesulonimi21** [comment]
@AwolDes 
Please let me know if i can deploy a new version of the contracts repo(internal/rc-v0.0.25) so that these commits can be tested.
Thanks

**Review by AwolDes — APPROVED** [review]
Happy with this & happy if we cut a new version of the contracts to test

**Comment by Jesulonimi21** [comment]
@AwolDes 
I have deployed a new contracts version and tested this and everything works fine. But the tests fail because I think reach updated something relating to secretKey in the last release so we get this error below:
```
    Malformed secret key, expected 32 bytes but got 64

      62 |       this.reachAccount = await this.reachStdLib.newAccountFromMnemonic(this.mnemonic);
      63 |     } else if (this.secretKey && !this.reachAccount) {
    > 64 |       this.reachAccount = await this.reachStdLib.newAccountFromSecret(this.secretKey);
         |                                                  ^
      65 |     } else if (
      66 |       this.networkAccount &&
      67 |       this.signer &&

      at protectSecretKey (node_modules/@reach-sh/stdlib/ts/shared_impl.ts:1352:11)
      at Object.newAccountFromSecret (node_modules/@reach-sh/stdlib/ts/ALGO.ts:2567:70)
      at MockVaultClient.<anonymous> (src/Account.ts:64:50)
      at src/Account.ts:8:71
      at Object.<anonymous>.__awaiter (src/Account.ts:4:12)
```
If I roll back to the reach version we were using before, we do not get the error

**Comment by AwolDes** [comment]
@Jesulonimi21 thanks mate - will ping Reach and check.

**Pull request merged**
